Server:
  RunModel : debug
  HttpPort : 8080
  ReadTimeOut : 60
  WriteTimeOut : 60
App:
  DefaultPageSize : 10
  MaxPageSize : 100
  LogSavePath : storage/logs
  LogFileName : app
  LogFileExt : .log
Database:
  DBType : mysql
  UserName : root
  Password : 123654
  Host : 114.215.139.30
  Port : 3306
  DBName : gin-test
  TablePrefix : blog_
  Charset : utf8
  ParseTime : True
  MaxIdleConns : 10
  MaxOpenConns : 30